### ISSUE TITLE
Exception when using with python 3.6

### ISSUE THREAD

**Issue by bparzella** [sinoroc/tox-poetry-dev-dependencies#51]
When running tox-poetry-dev-dependencies 0.0.5 with on python 3.6.8 I get an exception:

```
.tox recreate: D:\Data\package\.tox\.tox
.tox installdeps: tox-poetry-dev-dependencies == 0.0.5, tox >= 3.20.1
Traceback (most recent call last):
  File "c:\users\user\.pyenv\pyenv-win\versions\3.6.8\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\.pyenv\pyenv-win\versions\3.6.8\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Data\package\.tox\.tox\lib\site-packages\tox\__main__.py", line 4, in <module>
    tox.cmdline()
  File "D:\Data\package\.tox\.tox\lib\site-packages\tox\session\__init__.py", line 44, in cmdline
    main(args)
  File "D:\Data\package\.tox\.tox\lib\site-packages\tox\session\__init__.py", line 65, in main
    config = load_config(args)
  File "D:\Data\package\.tox\.tox\lib\site-packages\tox\session\__init__.py", line 81, in load_config
    config = parseconfig(args)
  File "D:\Data\package\.tox\.tox\lib\site-packages\tox\config\__init__.py", line 263, in parseconfig
    pm = get_plugin_manager(plugins)
  File "D:\Data\package\.tox\.tox\lib\site-packages\tox\config\__init__.py", line 79, in get_plugin_manager
    pm.load_setuptools_entrypoints("tox")
  File "D:\Data\package\.tox\.tox\lib\site-packages\pluggy\manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "D:\Data\package\.tox\.tox\lib\site-packages\importlib_metadata\__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "c:\users\user\.pyenv\pyenv-win\versions\3.6.8\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Data\package\.tox\.tox\lib\site-packages\tox_poetry_dev_dependencies\_hooks.py", line 5
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

Documentation states that this future was introduced in python 3.7.0b1.

**Comment by sinoroc** [comment]
Ouch! Thanks for the report. I will look at this soon.

**Comment by sinoroc** [comment]
@bparzella Any idea how projects deal with this kind of issues usually?

**Comment by sinoroc** [comment]
I got it, I will release a new version later today.

**Comment by bparzella** [comment]
> @bparzella Any idea how projects deal with this kind of issues usually?

I'd say things like version incompatibility are a question of (unit) testing. As tox supports testing against different python versions this is something that can be detected before publishing. At least that's how I'd do it.

**Comment by sinoroc** [comment]
@bparzella 
Yes, my test suite is a bit useless for such cases. It only takes care of linting and type checking, so that actual runtime issues are not (can not) be caught. I wish I was better at this. I was actually asking about how to deal with type hints, postponed evaluation of annotations (_PEP 563_), etc. But I figured it out. Release should be ready in a couple of minutes.

**Comment by bparzella** [comment]
@sinoroc 
Oh, sorry, I misunderstood that 😀

**Comment by sinoroc** [comment]
@bparzella 
Verion [_0.0.6_](https://pypi.org/project/tox-poetry-dev-dependencies/0.0.6/) just released. Please, give it a try and let me know if things are better or worse.

**Comment by bparzella** [comment]
@sinoroc
This seems to be working, but I get another error now. I'll create a new issue.
